# Generated by Django 3.1.3 on 2020-11-15 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='photos',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
